Add files via upload
MolineroA/common pull request #1
Opened 2019-09-27 09:08 UTC by MolineroA

2019-09-27 09:15 UTC, MolineroA reviewed
change function "alphabet"

2019-09-27 11:29 UTC, dimigor commented on homework.py
> +    if first == second:
Operators like `==, is, in` already return Bool value

2019-09-28 09:51 UTC, yuriimchg requested changes
привіт
пайтон-частина завдання зроблена дуже добре - все виглядає гарно, пайтонічно і без костилів :+1: 
однак в мене є декілька зауважень до стилізації: 
```
git/homework.py:7:19: E271 multiple spaces after keyword
git/homework.py:11:1: E303 too many blank lines (3)
git/homework.py:33:1: E303 too many blank lines (3)
git/homework.py:42:1: E303 too many blank lines (3)
git/homework.py:119:29: E211 whitespace before '('
git/homework.py:132:36: E225 missing whitespace around operator
git/homework.py:147:1: E303 too many blank lines (3)
git/homework.py:163:16: W292 no newline at end of file

```
їх можна легко побачити завдяки `flake8`: https://pypi.org/project/flake8/
також не додавай зайві файлики до комітів - це допоможе зробити `.gitignore`. Детальніше про .gitignore можна почитати тут: https://www.quora.com/Whats-the-purpose-of-a-gitignore-file

Крім того, варто викинути файлики `homework.py` і  `tests.py`, які не знаходяться в папці `git` - їх просто не потрібно :wink:

2019-09-28 09:51 UTC, yuriimchg commented on git/homework.py
> +    return [i for i in range (13) if i not in [6, 7]]
елегантне і читабельне рішення :+1:

2019-09-29 06:48 UTC, yuriimchg approved these changes
:+1: 
молодець

2019-09-29 10:43 UTC, merged